name: RDP with ZeroTier (Test Mode)

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Install ZeroTier
      run: |
        Invoke-WebRequest https://download.zerotier.com/dist/ZeroTierOne.msi -OutFile ZeroTierOne.msi
        Start-Process msiexec.exe -ArgumentList '/i ZeroTierOne.msi /quiet /norestart' -Wait
        Start-Sleep -Seconds 20

    - name: Debug - Search ZeroTier files
      run: |
        Write-Host "🔍 Searching for ZeroTier installation..."
        Get-ChildItem "C:\" -Recurse -ErrorAction SilentlyContinue | Where-Object { $_.Name -like "zerotier*" } | Select-Object FullName

    - name: Try Join ZeroTier Network
      env:
        ZT_NET_ID: ${{ secrets.ZT_NET_ID }}
      run: |
        $paths = @(
          "C:\ProgramData\ZeroTier\One\zerotier-cli.bat",
          "C:\Program Files (x86)\ZeroTier\One\zerotier-cli.bat",
          "C:\Program Files\ZeroTier\One\zerotier-cli.bat"
        )

        $found = $false
        foreach ($p in $paths) {
          if (Test-Path $p) {
            Write-Host "✅ Found CLI at $p"
            & $p join $Env:ZT_NET_ID
            $found = $true
            break
          }
        }

        if (-not $found) {
          Write-Error "❌ ZeroTier CLI not found in common paths. Check debug step above."
        }

    - name: Enable RDP + Set Password
      run: |
        net user runneradmin MyPassword123!
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Show ZeroTier IP
      run: ipconfig

    - name: Keep Alive
      run: |
        while ($true) { Start-Sleep -Seconds 300 }
