name: RDP with ZeroTier

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Install ZeroTier
      run: |
        Invoke-WebRequest https://download.zerotier.com/dist/ZeroTierOne.msi -OutFile ZeroTierOne.msi
        Start-Process msiexec.exe -ArgumentList '/i ZeroTierOne.msi /quiet /norestart' -Wait

    - name: Join ZeroTier Network
      env:
        ZT_NET_ID: ${{ secrets.ZT_NET_ID }}
      run: Start-Process "C:\Program Files\ZeroTier\One\zerotier-one_x64.exe" -ArgumentList "join $Env:ZT_NET_ID" -Wait

    - name: Enable RDP + Set Password
      run: |
        net user runneradmin MyPassword123!
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Show ZeroTier IP
      run: ipconfig

    - name: Keep Alive
      run: |
        while ($true) { Start-Sleep -Seconds 300 }
