name: Linux RDP via Husarnet

on:
  workflow_dispatch:
    inputs:
      rdp_user:
        description: "RDP Username"
        required: false
        default: "hnuser"
      rdp_pass:
        description: "RDP Password"
        required: false
        default: "HusarnetPass123"
      runtime_minutes:
        description: "RDP Alive Minutes (max 355)"
        required: false
        default: "355"

jobs:
  rdp:
    runs-on: ubuntu-latest
    timeout-minutes: 370
    steps:
      - name: Update and install essentials
        run: |
          sudo apt-get update
          sudo apt-get install -y xrdp xfce4 xfce4-goodies
          sudo apt-get install -y wget curl git htop neofetch
          sudo adduser --disabled-password --gecos "" ${{ github.event.inputs.rdp_user }}
          echo "${{ github.event.inputs.rdp_user }}:${{ github.event.inputs.rdp_pass }}" | sudo chpasswd

      - name: Install Husarnet
        run: |
          curl -s https://install.husarnet.com/install.sh | sudo bash

      - name: Connect to Husarnet
        run: |
          sudo husarnet join "${{ secrets.HUSARNET_JOINCODE }}" linux-gha-rdp
          sudo husarnet status

      - name: Configure xRDP for new user
        run: |
          echo "startxfce4" | sudo tee /home/${{ github.event.inputs.rdp_user }}/.xsession
          sudo chown ${{ github.event.inputs.rdp_user }}:${{ github.event.inputs.rdp_user }} /home/${{ github.event.inputs.rdp_user }}/.xsession
          sudo adduser ${{ github.event.inputs.rdp_user }} ssl-cert
          sudo systemctl restart xrdp

      - name: Display Husarnet IPv6 address
        run: |
          sudo husarnet status

      - name: Keep RDP session alive
        run: |
          export END=$((SECONDS + ${{ github.event.inputs.runtime_minutes }} * 60))
          while [ $SECONDS -lt $END ]; do
            echo "RDP alive for $(( (${END} - $SECONDS) / 60 )) min left..."
            sleep 60
          done
